In [3]:
import pandas as pd
import numpy as np

In [7]:
# CSV-Datei laden
# https://www.kaggle.com/datasets/akashbommidi/super-market-sales/data
df = pd.read_csv('supermarket_sales.csv') # Dateipfad übergeben
# Erste 5 Zeilen anzeigen
df.head()
df.tail()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

## Alternativ: Download direkt von Kaggle
Am Beispiel von IRIS Dataset

In [1]:
import kagglehub
import pandas as pd
import os

path = kagglehub.dataset_download("endofnight17j03/iris-classification") # Pfad aus Kaggle
print(os.listdir(path)) # nach dem Download herausfinden wie die csv Datei heißt

df = pd.read_csv(os.path.join(path, "IRIS.csv")) # Name der csv Datei anpassen
df.head()

/Users/schoch/Documents/0_Vorlesungen/GrundlagenDSKI/DSKI_WDS26B2_Teil1/2025Git/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: Looks like you're using an outdated `kagglehub` version (installed: 1.0.2), please consider upgrading to the latest version (1.0.3)['IRIS.csv']

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## Analyse des Supermarket Sales Dataset

In [8]:
# Anzeige der Spaltenbezeichnungen
print('Spalten: ', df.columns)

# Index - Zeilen haben typischerweise einen numerischen Index, können aber z.B. auch vom Typ String sein
print(df.index)

Spalten:  Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='object')
RangeIndex(start=0, stop=1000, step=1)

In [9]:
# Übersicht und statistische Werte
df.describe()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

In [11]:
# Übersicht und statistische Werte von Variablen vom typ Object
df.describe(include="all")

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
count,1000,1000,1000,1000,1000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000,1000,1000.00000,1000.000000,1000.000000,1000.00000
unique,1000,3,3,2,2,6,NaN,NaN,NaN,NaN,89,506,3,NaN,NaN,NaN,NaN
top,750-67-8428,A,Yangon,Member,Female,Fashion accessories,NaN,NaN,NaN,NaN,2/7/2019,19:48,Ewallet,NaN,NaN,NaN,NaN
freq,1,340,340,501,501,178,NaN,NaN,NaN,NaN,20,7,345,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,55.672130,5.510000,15.379369,322.966749,NaN,NaN,NaN,307.58738,4.761905,15.379369,6.97270
std,NaN,NaN,NaN,NaN,NaN,NaN,26.494628,2.923431,11.708825,245.885335,NaN,NaN,NaN,234.17651,0.000000,11.708825,1.71858
min,NaN,NaN,NaN,NaN,NaN,NaN,10.080000,1.000000,0.508500,10.678500,NaN,NaN,NaN,10.17000,4.761905,0.508500,4.00000
25%,NaN,NaN,NaN,NaN,NaN,NaN,32.875000,3.000000,5.924875,124.422375,NaN,NaN,NaN,118.49750,4.761905,5.924875,5.50000
50%,NaN,NaN,NaN,NaN,NaN,NaN,55.230000,5.000000,12.088000,253.848000,NaN,NaN,NaN,241.76000,4.761905,12.088000,7.00000
75%,NaN,NaN,NaN,NaN,NaN,NaN,77.935000,8.000000,22.445250,471.350250,NaN,NaN,NaN,448.90500,4.761905,22.445250,8.50000
max,NaN,NaN,NaN,NaN,NaN,NaN,99.960000,10.000000,49.650000,1042.650000,NaN,NaN,NaN,993.00000,4.761905,49.650000,10.00000

In [13]:
# Überblick über Datentypen und fehlende Werte
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [14]:
# Ausgabe aller Rechnungen mit mehr als 100$
df[df.Total>100] # Alternativ df[df['Total']>100]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,602-16-6955,B,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,18:10,Ewallet,766.00,4.761905,38.3000,6.0
992,745-74-0715,A,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,20:46,Ewallet,116.06,4.761905,5.8030,8.8
993,690-01-6631,B,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,18:35,Ewallet,174.90,4.761905,8.7450,6.6
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [15]:
# Prüfen ob Unit Price*Quantity = Total? Die Summe darüber müsste 0 sein
print('Summe über  Total-Unit price*quantity: ', sum(df['Total']-df['Unit price']*df['Quantity']))

# Prüfen ob der Stückpreis noch ohne Steuer ist
print('Summe über Total-Unit price*1.05*quantity: ',sum(df['Total']-df['Unit price']*1.05*df['Quantity'])) # 5% tax auf den Unit price

Summe über  Total-Unit price*quantity:  15379.368999999999
Summe über Total-Unit price*1.05*quantity:  -1.3997691894473974e-11

In [16]:
# Total nach City gruppieren, wie viel wird insgesamt je Stadt ausgegeben

print('\n') # Newline in der Ausgabe

# Wie hoch ist Total im Schnitt je Geschlecht
total_per_gender = df.groupby('Gender')['Total'].mean()
print(total_per_gender)
print('\n')

# Kategorie nach Gender gruppieren
gender_product_line = df.groupby(['Product line', 'Gender']).size()
print(gender_product_line)

Gender
Female    335.095659
Male      310.789226
Name: Total, dtype: float64


Product line            Gender
Electronic accessories  Female    84
                        Male      86
Fashion accessories     Female    96
                        Male      82
Food and beverages      Female    90
                        Male      84
Health and beauty       Female    64
                        Male      88
Home and lifestyle      Female    79
                        Male      81
Sports and travel       Female    88
                        Male      78
dtype: int64

## Korrelation von kardinal skalierten Variablen

In [17]:
# Auswahl der Spalten 
kardinal_columns = ['Unit price', 'Quantity', 'Tax 5%', 'Total', 'cogs', 'gross margin percentage', 'gross income', 'Rating']
df[kardinal_columns].corr()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
Unit price,1.000000,0.010778,0.633962,0.633962,0.633962,NaN,0.633962,-0.008778
Quantity,0.010778,1.000000,0.705510,0.705510,0.705510,NaN,0.705510,-0.015815
Tax 5%,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
Total,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
cogs,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
gross margin percentage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gross income,0.633962,0.705510,1.000000,1.000000,1.000000,NaN,1.000000,-0.036442
Rating,-0.008778,-0.015815,-0.036442,-0.036442,-0.036442,NaN,-0.036442,1.000000

In [18]:
# Gross margin percentage ist konstant
print(df['gross margin percentage'].unique())

kardinal_columns = ['Unit price', 'Quantity', 'Tax 5%', 'Total', 'cogs', 'gross income', 'Rating']
df[kardinal_columns].corr()

[4.76190476]

,Unit price,Quantity,Tax 5%,Total,cogs,gross income,Rating
Unit price,1.000000,0.010778,0.633962,0.633962,0.633962,0.633962,-0.008778
Quantity,0.010778,1.000000,0.705510,0.705510,0.705510,0.705510,-0.015815
Tax 5%,0.633962,0.705510,1.000000,1.000000,1.000000,1.000000,-0.036442
Total,0.633962,0.705510,1.000000,1.000000,1.000000,1.000000,-0.036442
cogs,0.633962,0.705510,1.000000,1.000000,1.000000,1.000000,-0.036442
gross income,0.633962,0.705510,1.000000,1.000000,1.000000,1.000000,-0.036442
Rating,-0.008778,-0.015815,-0.036442,-0.036442,-0.036442,-0.036442,1.000000

## Nominal skalierte Varialben

In [19]:
from scipy.stats.contingency import association

# Kontingenztabelle erstellen und ausgeben
ct = pd.crosstab(df['Product line'], df['Gender'])
print(ct)
# Berechnen und Ausgabe von Cramers V
print('Cramers V zwischen Product Line und Gender: ', association(ct, method="cramer"))

ct = pd.crosstab(df['Gender'], df['Payment'])
print(ct)
print('Cramers V zwischen Payment und Gender: ', association(ct, method="cramer"))


ct = pd.crosstab(df['City'], df['Customer type'])
print(ct)
print('Cramers V zwischen City und Customer type: ', association(ct, method="cramer"))

Gender                  Female  Male
Product line
Electronic accessories      84    86
Fashion accessories         96    82
Food and beverages          90    84
Health and beauty           64    88
Home and lifestyle          79    81
Sports and travel           88    78
Cramers V zwischen Product Line und Gender:  0.07579218864489033
Payment  Cash  Credit card  Ewallet
Gender
Female    178          163      160
Male      166          148      185
Cramers V zwischen Payment und Gender:  0.05431098711683407
Customer type  Member  Normal
City
Mandalay          165     167
Naypyitaw         169     159
Yangon            167     173
Cramers V zwischen City und Customer type:  0.02046485450067572

## Beispiel Titaic Dataset

In [20]:
import seaborn as sns
titanic = sns.load_dataset('titanic') # Der Datensatz kann aus der Seaborn Bibliothek direkt geladen werden
titanic.head()

Matplotlib is building the font cache; this may take a moment.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [21]:
ct = pd.crosstab(titanic['sex'], titanic['survived'])
print(ct)
print('Cramers V zwischen Geschlecht und survived: ', association(ct, method="cramer"))

ct = pd.crosstab(titanic['sex'], titanic['alone'])
print(ct)
print('Cramers V zwischen Geschlecht und alone: ', association(ct, method="cramer"))

survived    0    1
sex
female     81  233
male      468  109
Cramers V zwischen Geschlecht und survived:  0.5433513806577551
alone   False  True
sex
female    188    126
male      166    411
Cramers V zwischen Geschlecht und alone:  0.30364618554380884